[[Build-documentation]]
= Building Neo4j =

1.1 <<Introduction, Introduction>>

1.2 <<target, For whom is this document intended?>>

1.3 <<Motivation, Motivation>>

2.1 <<Matrix, Test Matrix>>

3.1 <<Platforms, Platforms>>

3.2 <<Debian-Ubuntu, Debian & Ubuntu>>

3.3 <<OSX,OS X >>

3.4 <<Windows7, Windows 7>>

[[Introduction]]

== Introduction ==

This document describes the build process used by Neo4j Community Edition,
and is intended as both full replacement for the current documentation out
there as well as an addition to the Neo4j user manual.

[[target]]
=== For whom is this document intended? ===

Currently it is more difficult than necessary to get started with Neo4j,
especially setting up the project so that it will build. +
This document was written with external developers looking to contribute
to Neo4j in mind.

[[Motivation]]
=== Motivation ===

The motivation for this document was born out of a desire on the part of the
team (formed in the context of the Software Architecture course) to have an
easily accessible place that clearly explains how to build the Neo4j Community
Edition system instead of the current situation in which build documentation is
scattered over at least 3 places within the neo4j Github repository.

[[Matrix]]
== Test matrix ==

// The test matrix can tell you where Java 6 and 7 will and won't work.
// *Yes* means that the combination of OS ans Java version has been
// tested and has been found to work, while a *no* means the combination
// won't work. A *?* in the table means that the combination has not been
// tested or non-conclusive results were found.

The test matrix below contains various popular system configurations and the results our
team got in trying to build Neo4j on it.

NOTE: The Java environments used on Linux were the OpenJDK variants unless stated otherwise.

NOTE: The Java environments used on OS X were Apple's version for Java 6 and Oracle's JVM 7.

+++
<table border="4">
       <th> OS           <th> bits                <th> JDK <th> Used flags                                                <th> Builds properly?
<tr> <td> Ubuntu 12.04 <td align="center">  64  <td align="center">  6  <td>                                            <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT                                    <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DfullBuild                                <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -Dmaven.test.skip=true                     <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -DfullBuild                        <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -Dmaven.test.skip=true             <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DfullBuild -Dmaven.test.skip=true         <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true <td align="center"> true
<tr> <td>              <td>                     <td>                    <td>                                            <td>
<tr> <td> Ubuntu 12.04 <td align="center">  64  <td align="center">  7  <td>                                            <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT                                    <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DfullBuild                                <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -Dmaven.test.skip=true                     <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -DfullBuild                        <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -Dmaven.test.skip=true             <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DfullBuild -Dmaven.test.skip=true         <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true <td align="center"> true
<tr> <th> OS           <th> bits                <th> JDK <th> Used flags                                                <th> Builds properly?
<tr> <td> Ubuntu 13.04 <td align="center">  64  <td align="center">  6  <td>                                            <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT                                    <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DfullBuild                                <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -Dmaven.test.skip=true                     <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -DfullBuild                        <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -Dmaven.test.skip=true             <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DfullBuild -Dmaven.test.skip=true         <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true <td align="center"> true
<tr> <td>              <td>                     <td>                    <td>                                            <td>
<tr> <td> Ubuntu 13.04 <td align="center">  64  <td align="center">  7  <td>                                            <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT                                    <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DfullBuild                                <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -Dmaven.test.skip=true                     <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -DfullBuild                        <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -Dmaven.test.skip=true             <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DfullBuild -Dmaven.test.skip=true         <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true <td align="center"> true
<tr> <th> OS           <th> bits                <th> JDK                <th> Used flags                                 <th> Builds properly?
<tr> <td> OS X 10.7    <td align="center">  64  <td align="center">  6  <td>                                            <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT                                    <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DfullBuild                                <td align="center"> false
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -Dmaven.test.skip=true                     <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -DfullBuild                        <td align="center"> false
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -Dmaven.test.skip=true             <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DfullBuild -Dmaven.test.skip=true         <td align="center"> false
<tr> <td>              <td align="center">  64  <td align="center">  6  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true <td align="center"> false
<tr> <td>              <td>                     <td>                    <td>                                            <td>
<tr> <td> OS X 10.7    <td align="center">  64  <td align="center">  7  <td>                                            <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT                                    <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DfullBuild                                <td align="center"> false
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -Dmaven.test.skip=true                     <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -DfullBuild                        <td align="center"> false
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -Dmaven.test.skip=true             <td align="center"> true
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DfullBuild -Dmaven.test.skip=true         <td align="center"> false
<tr> <td>              <td align="center">  64  <td align="center">  7  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true <td align="center"> false
<tr> <th> OS           <th> bits                <th> JDK                <th> Used flags                                 <th> Builds properly?
<tr> <td> Win 7 Prof.  <td align="center">  32  <td align="center">  6  <td>                                            <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -Dlicensing.skip                           <td align="center"> true
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DrunIT                                    <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DrunIT -Dlicensing.skip                   <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DfullBuild                                <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DfullBuild -Dlicensing.skip               <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -Dmaven.test.skip=true                     <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -Dmaven.test.skip=true -Dlicensing.skip    <td align="center"> true
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DrunIT -DfullBuild                        <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DrunIT -DfullBuild -Dlicensing.skip       <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DrunIT -Dmaven.test.skip=true             <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DrunIT -Dmaven.test.skip=true
                                                                                                                  -Dlicensing.skip             <td align="center"> true
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DfullBuild -Dmaven.test.skip=true         <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DfullBuild -Dmaven.test.skip=true
                                                                                                                  -Dlicensing.skip             <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  6  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true
                                                                                                                        -Dlicensing.skip       <td align="center"> false
<tr> <td> Win 7 Prof.  <td align="center">  32  <td align="center">  7  <td>                                            <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -Dlicensing.skip                           <td align="center"> true
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DrunIT                                    <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DrunIT -Dlicensing.skip                   <td align="center"> true
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DfullBuild                                <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DfullBuild -Dlicensing.skip               <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -Dmaven.test.skip=true                     <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -Dmaven.test.skip=true -Dlicensing.skip    <td align="center"> true
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DrunIT -DfullBuild                        <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DrunIT -DfullBuild -Dlicensing.skip       <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DrunIT -Dmaven.test.skip=true             <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DrunIT -Dmaven.test.skip=true
                                                                                                                  -Dlicensing.skip             <td align="center"> true
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DfullBuild -Dmaven.test.skip=true         <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DfullBuild -Dmaven.test.skip=true
                                                                                                                  -Dlicensing.skip             <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true <td align="center"> false
<tr> <td>              <td align="center">  32  <td align="center">  7  <td> -DrunIT -DfullBuild -Dmaven.test.skip=true
                                                                                                                        -Dlicensing.skip       <td align="center"> false
<tr> <th> OS           <th> bits                <th> JDK                <th> Used flags                                 <th> Builds properly?
</table>
+++
 +
There are consistently failing OS X builds and Windows builds that are not so easily fixed. +
As these failures appear to be related to performing a full build (i.e.
passing the _-DfullBuild_ flag), an issue has been opened about it https://github.com/neo4j/neo4j/issues/875[here].

[[Platforms]]
== Platforms ==

There are several platform specific instructions which will be handled
in the section below, there are however maven instructions which are
honored on every platform:

* _fullBuild_ -  This will build  all packages (community,  advanced and
  enterprise) as well as documentation
* _runITs_ - runs integration testing as well
* _maven.test.skip=true_ - tells maven to skip tests
* _licensing.skip_ - Skips the licensing checks during a build

The parameters above can be invoked by passing them with a '-D' prefix
e.g.  `mvn clean install -DfullBuild`

NOTE: Some tests have specific machine context demands, the following
list is not complete but gives an idea about implicit demands: +
 +
1. the build machine's socket localhost:8888 should not be used by
  other programs +
2. In case of vague errors, try to run maven with the parameter `-e` for
  more extensive error output or `-X` from debug output

.Dependencies

* maven

[[Debian-Ubuntu]]
=== Debian & Ubuntu Linux ===

Read this section if you want to know how to get Neo4j up and
running under Debian or Ubuntu Linux.

These instruction are with respect to a clean debian 7/Ubuntu 13.04 install.
Specific installation instructions for the dependencies: +
`apt-get install --no-install-recommends -y maven openjdk-7-jdk asciidoc docbook docbook-xml xsltproc libxml2-utils make w3m graphviz devscripts debhelper fakeroot build-essent$

Neo4j can then be build by issuing +
`mvn clean install`

NOTE: after installing openjdk 7, it can be the case openjdk-6 is
still installed and used as default JVM, remove the JDK6 from the
machine, or use the linux-alternatives framework to set the opendk-7
as default

.Hardware

NOTE: The machine should have more than 2GB for several tests to run,
otherwise the JVM does not allocate enough memory and it will be hit
or miss for more elaborate tests.

You can also look at <<using-vagrant>> for setting up a build environment.
[[OSX]]
=== OS X ===

Read this section if you want to know how to get Neo4j up and
running under Mac OS X.

IMPORTANT: As of June 6th 2013, the
https://github.com/delftswa/neo4j/blob/master/community/README.md[README.md]
of the community edition contains +
incorrect information w.r.t. building the community edition of Neo4j on OS X.

NOTE: Unless otherwise specified, the used JDK versions are 6 +
      (distributed by Apple) and 7 (distributed by Oracle).

You can build Neo4j on OS X by performing the following steps:

1. `export JAVA_OPTS="-Xms384M -Xmx512M -XX:MaxPermSize=256M"`

2. `git clone git://github.com/neo4j/neo4j.git community`

3. `mvn clean install`

4. *(OPTIONAL)* if you're having problems building Neo4j on OS X, then execute +
   `mvn clean install -X -U -Dmaven.test.skip=true` +
   instead of `mvn clean install`

NOTE: Trying to do either full builds or integration testing on OS X
will result in build failure, +
even when the `-Dmaven.test.skip=true` flag is passed.

[[Windows7]]
=== Windows 7 ===

Read this section if you want to know how to get Neo4j up and
running under Windows.

These instruction are with respect to a clean Windows 7 Professional install.
Apache Maven and JDK 1.6 or 1.7 is required to be installed on your machine.

Neo4j can then be build by issuing +
`mvn clean install`

NOTE: The build flag Dlicensing.skip is always required.

NOTE: DfullBuild fails due to unknown dependencies or settings that are required to build the manuals (19-06-2013)


//  LocalWords:  Vagrantfile
